- bin/coverage
- package.json
- tasks/coverage.js
This prints the coverage reports after the tests are run. Though adding it as a separate step, but that would mean tests are run twice, which can be very expensive for some of our modules that have very long tests.
Also, by printing the reports but not strictly enforcing a coverage minimum, we make devs aware of how the changes impacted the overall coverage.
What do you think?
> print coverage report

- config/webpack.js
Make js-ipfs a lot smaller. Ref https://github.com/ipfs/js-ipfs/issues/398
> feat(webpack): enable dedupe plugin

- config/eslintrc.yml
> feat(lint): restrict nesting to avoid callback hell

- config/babel.js
- config/karma.conf.js
- config/webpack.js
- package.json
Closes #36
BREAKING CHANGE:
This can break browser builds and tests and needs to be tested
carefully when upgrading.
> feat: do not depend on babel-polyfill

- README.md
- package.json
- src/utils.js
- tasks/release/bump.js
- tasks/release/changelog.js
- tasks/release/commit.js
- tasks/release/github.js
- tasks/release/post-build.js
As discussed in #30 this adds the first round of functionality to `aegir-release` to give us a base level of things.
- Generate `CHANGELOG.md` based on git log following the proposed commit message convention
- Generate a github release on the same basics
- The ability to skip this process by using `--no-changelog`
> Changelog generation

- config/karma.conf.js
Because: https://github.com/ipfs/js-ipfs-unixfs-engine/pull/64#issuecomment-245770818
related: https://github.com/dignifiedquire/aegir/issues/48
> Add a way to disable PhantomJS testing

- README.md
- config/user.js
- config/webpack.js
- tasks/build/browser.js
- tasks/lint.js
This PR will make it possible to specify the entry file for webpack.
The entry file is specified in `.aegir.js.` with field `entry`. Users of aegir will need to add `.aegir.js` file to their project's root directory and specify the entry point, eg:
```javascript
module.exports = {
entry: "src/browser-index.js",
}
```
Webpack will use the specified file as the entry point and output it to `dist/<filename>`, eg. `dist/browser-index.js`.
If `.aegir.js` file is present in the project, webpack will use `src/index.js` as the default entry file.
> Add possibility to specify entry file for webpack

- bin/coverage
- package.json
Coveralls is the default, you can select codecov in your package.json
file by adding `--provider=codecov` to the `coverage-publish` script.
> coverage: add codecov to coverage providers and allow to select it

- CHANGELOG.md
- bin/test
- package.json
- tasks/release/browser.js
- tasks/test/browser.js
This is a POC to add support for running tests in webworkers. I'm using this karma plugin - https://github.com/Joris-van-der-Wel/karma-mocha-webworker, it seems to get the job done and it allows running _all_ tests inside a webworker. @dignifiedquire @diasdavid please let me know what you think.
> POC: Add support to run tests in web workers

- src/config/jest.js
This fixes the issue where /src/ couldn't be a part of the full path and makes sure we only match from our workspace
Closes #150
> Add <rootDir> to ignore patterns for jest

- cmds/coverage.js
- cmds/release.js
- cmds/test.js
- src/test/node.js
Mocha 3 defaulted to force exit processes after tests were done. In Mocha 4 this is not the case anymore. As some tests/implementations are currently not properly cleaning up after themselves this adds this option back by default. 
References:
- https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#default-behavior
- https://github.com/mochajs/mocha/issues/2879
- https://www.npmjs.com/package/why-is-node-running
- https://boneskull.com/mocha-v4-nears-release/
> fix: add exit option back to fix buggy tests

- package.json
This issue is a patch until this PR https://github.com/roadhump/karma-mocha-own-reporter/pull/3 is merged
> fix: karma own reported bug with missing test.titlePath

- src/test/node.js
adding `--timeout` flag for mocha runs as well as increasing timeout to 5000, same as jest.
> feat: add timeout flag for mocha runs and increase default to 5000

- src/test/node.js
@dignifiedquire coverage tests are timing out due to default of 2000ms, this should set the timeout to the expected 5000ms.
> feat: add timeout to coverage

- cmds/docs.js
- cmds/release.js
- src/docs/build.js
- src/utils.js
Look what I made \o/
This is for ipfs/docs#43
> feat(docs): add flag for building markdown docs

- src/build/browser.js
For some reason, Uglify is messing up with some variables on js-ipfs. Here's a quick fix.
This closes https://github.com/ipfs/js-ipfs/issues/1131
> Fix messed-up variables

- src/release/prerelease.js
If you want to publish a package on npm you need to provide
a GitHub access token. This is normally done through the
`AEGIR_GHTOKEN` environment variable. Add this information to
the error message if such a token is missing.
> docs: give advice on aegir release error

- src/release/commit.js
- src/release/push.js
Projects are moving from pre-commit hook to pre-push hooks.
Linting and testing is already done in separate steps before
the push, hence don't run the pre-push hook when pushing to
GitHub.
Fixes #192.
> Don't verify on push

- README.md
- src/fixtures.js
- test/browser.spec.js
needed for: https://github.com/ipfs/js-ipfs-api/pull/689
**warning: this is a breaking change for how fixtures get loaded**
> feat: allow to load fixtures from paths other than ./test

- src/config/karma.conf.js
By default, karma loads plugins from sibling modules that starts with
`karma-*`. When a package manager (yarn in this case) has a version
conflict, node_modules turns into a tree with nested node_modules/
instead of 100% flat. This makes karma not be able to get the module.
This fix makes it explicitly which plugins we want to load, so it can
work in any of the node_modules modes (tree vs flat)
> Explicitly load plugins for karma

- src/config/karma-webpack-bundle.js
- src/config/karma.conf.js
- src/config/webpack/index.js
- src/test/browser-config.js
Prior to this commit there was a webpack bundle created for every test
file. That lead to very high memory usage when running the Browser tests.
Now there's a single bundle.
> fix: make a single webpack bundle

- src/config/karma-webpack-bundle.js
- src/config/webpack/index.js
Check if `test/browser.js` exist before webpack is initiated and require
it only if it really exist. This makes a warning go away that lead to
a lot of console output.
Fixes #204.
> fix: don't show warning if test/browser.js doesn't exist

- src/config/webpack/index.js
- test/config/webpack.spec.js
Uses inline-source-map for webpack when running the tests. This will
then give accurate line numbers for failing tests.
> feat: add inline-source-map for webpack

- src/build/browser.js
We can now enable **mangling** after changing the way we did some type checking, from comparing instances with `constructor.name` to using the [class-is](https://github.com/moxystudio/js-class-is) module that uses symbols, as proposed in https://github.com/ipfs/js-ipfs/issues/1131#issuecomment-373299739.
Check https://github.com/ipfs/js-ipfs/issues/938#issuecomment-377945902 for some of the repos that were affected.
We can now also **compress** the code, but I've had to disable the `unused` flag (it drops unreferenced functions and variables -- [check it](https://github.com/mishoo/UglifyJS2#compress-options)) due to the following error:
```js
Uncaught (in promise) Error: Callback was already called
```
Fixes https://github.com/ipfs/js-ipfs/issues/938.
> feat: enable uglify mangle and compress

- test/test.spec.js
Won't require any release as it's more of a informative test-case rather than an actual feature. The feature itself is built-in in mocha.
> Test case for retries in mocha

- cmds/build.js
- cmds/coverage.js
- cmds/docs.js
- cmds/lint.js
- cmds/release.js
- cmds/test.js
- src/test/index.js
This makes the CLI a lot faster as aegir only have to load required commands
when it's actually needed, not always. Every command gets faster as well
since it only loads what needed (node tests don't need to load Karma
anymore for example)
This branch:
`time node cli.js` => ~0.2 seconds
`time node cli.js test` => ~1.6 seconds
Current master:
`time node cli.js` => ~1.0 seconds
`time node cli.js test` => ~2.1 seconds
> Inline requires in CLI inclusions

- src/fixtures.js
- test/fixtures.spec.js
- test/fixtures/resolve-test/node_modules/dep-a/fixture.txt
- test/fixtures/resolve-test/project-dir/fixtures.spec.js
- test/fixtures/resolve-test/project-dir/node_modules/aegir/fixtures.js
The current implementation of `/src/fixtures.js` only takes a few paths into account when trying to load a fixture.  This PR adds using `require.resolve` to attempt to load a fixture too.
This is useful if you are running a monorepo and are using aegir to simplify your build process - in this case shared dependencies may have been be hoisted to a directory higher up the tree.  Trying to require fixtures using aegir fails at the moment when this is the case.
> feat: Allow loading resources from hoisted dependencies

- src/config/karma.conf.js
- src/test/browser-config.js
- src/test/node.js
This makes it so if we run many tests concurrently in CI, the test-reports will not overwrite each other.
Contains one revert that I will remove as soon as @achingbrain submitted a fix for the issue it introduced.
> Junit random suffix

- README.md
For passing to a bundle visualizer like https://chrisbateman.github.io/webpack-visualizer/
> docs: instruction on how to get webpack stats data

- src/lint.js
- test/lint.spec.js
Currently the lint task for `interface-ipfs-core` is passing because the [default globs](https://github.com/ipfs/aegir/blob/46ba7165666a1034f01b82bca63517698da8701b/src/lint.js#L9-L19) do not include the `js/` prefix. This PR allows the user to configure the globs for files that should be linted.
> feat: add ability for user to configure linted files

- package.json
With the change from `pre-push` to `git-validate` there was an issue
when you were removing `node_modules` before upgrading to AEgir 15.0.0.
(see https://github.com/ipfs/js-ipfs/issues/1444 for more).
On the most recent version of git-validate that issue was fixed.
> fix: make AEgir upgrade smoother

- cmds/test.js
- package.json
- src/test/browser-config.js
- src/test/node.js
- src/utils.js
Also specify files to run for node tests, as there is no test/node.js or test/**/*.spec.js
files.
The output for tests on some color setups is unreadable, disabling
colors helps this immensely.
As I started to bring up in
https://github.com/ipfs/interface-ipfs-core/issues/325, there isn't a
clean way to isolate tests built into the setup currently. Adding the
grep option gives this to us.
> feat: add grep and colors option to test

- src/test/browser.js
Fix for https://github.com/ipfs/aegir/issues/212
Doesn't leave any browsers around (they already exited at this point anyways)
@dignifiedquire can you review this?
License: MIT
> fix: windows takes 2 minutes to exit

- package.json
- src/config/karma.conf.js
- test/utils.spec.js
Accepts a comma-separated list of browsers or just one browser without
any commas.
Example to run in Chrome + Firefox
```console
AEGIR_BROWSERS='Firefox,Chrome' npm run test:browser
```
Fixes https://github.com/ipfs/aegir/issues/124
License: MIT
> feat: set browsers with AEGIR_BROWSERS

- package.json
- src/build/browser.js
- src/config/webpack/index.js
- test/acceptance.sh
- test/config/webpack.spec.js
Setting the webpack mode to `production` seems to automatically minify
the source, so by explicitly setting it to `development`, we get a
unminified build and a minified one.
License: MIT
> [WIP] fix: unminified builds should not be minified

- src/release/index.js
Relatively straightforward change, makes `aegir release` do the bump
before the release.
Fixes #208
License: MIT
> fix: bump version before building

- src/config/eslintrc.js
This PR only removes the requirement when the function doesn't actually return  like when using callbacks.
check this https://eslint.org/docs/rules/valid-jsdoc#options
option description
> "requireReturn" requires a return tag:
> true (default) even if the function or method does not have a return statement (this option value does not apply to constructors)
> false if and only if the function or method has a return statement or returns a value e.g. async function (this option value does apply to constructors)
> remove requirement to include @returns in jsdoc

- src/utils.js
The new version of aegir logs a `TypeError` whenever the `.aegir.js` file is missing for every command, which is very annoying. It doesn't break anything, just a UX issue.
This just makes sure we don't try to require the file if it doesn't exist.  I linked this to a couple of modules and ran `lint` and `test` commands to verify the fix.
> fix: dont require missing config

- package.json
- src/docs/build.js
documentation.js uses a browser specific resolve algo so with stuff like this
```
"browser": {
"hapi": false,
"glob": false,
"fs": false,
"joi": false,
"stream": "readable-stream",
"http": "stream-http",
"./src/utils/repo/nodejs.js": "./src/utils/repo/browser.js",
"./src/utils/exec.js": false,
"./src/utils/find-ipfs-executable.js": false,
"./src/utils/tmp-dir.js": "./src/utils/tmp-dir-browser.js",
"./src/utils/run.js": false,
"./src/factory-daemon.js": false,
"./src/ipfsd-daemon.js": false,
"./src/endpoint/server.js": false,
"./src/endpoint/routes.js": false,
"./test/utils/df-config-nodejs.js": "./test/utils/df-config-browser.js"
},
```
some files will not be found and no documentation generated.
With this PR i fix this with a fork of documentation.js that uses node resolve algo until we …
> fix: fix documentation.js not loading files and change input file

- src/lint.js
In the context of this discussion thread [js-ipfs#1678#pullrequestreview-169411876](https://github.com/ipfs/js-ipfs/pull/1678#pullrequestreview-169411876). 
Examples should have their own linting.
> chore: remove examples from linting

- src/lint.js
This PR adds support to override eslint config with a .eslintrc.* file or an eslintConfig field in a package.json file. 
Basically using `configFile` with `useEslintrc: true` doesn't work because `configFile` takes precedence over anything coming from the current repo. 
/cc @PedroMiguelSS, @diasdavid
> feat: add support for eslint overrides

- package.json
- src/config/eslintrc.js
We've all done this. Committed a `.only` in a test file and wondered why the build was so fast. Or had a reviewer helpfully point out why the coverage has dropped so dramatically.
> feat: add rule to catch `.only` in tests

- package.json
- src/config/babelrc.js
- src/config/webpack.config.js
- src/utils.js
This PR makes  experimental babel/webpack config safer, faster and more compatible with the default one and bundle smaller.
> fix: make babel and webpack safer and faster

- src/config/karma.conf.js
If you are running lerna or another monorepo tool it's common to hoist your dependencies into a parent directory.
The loading of karma tests assumes aegir is in the node_modules directory of your project, which may not be the case if it's been hoisted.
This change loads the `karma-entry.js` file from the current directory instead of the hardcoded node_modules path to ensure that you can actually run your browser tests in a monorepo setup.
It also only adds `karam-entry.js` if we haven't specified custom files to test.
> fix: pull in karma-entry.js from current directory

- README.md
Patch prerelease is using `preminor` instead of `prepatch`
> chore: fix patch prerelease command snippet

- src/config/karma.conf.js
There are some cases where it doesn't connect to Chrome and you get errors like:
```sh
13 02 2019 11:54:23.451:ERROR [launcher]: ChromeHeadless failed 2 times (timeout). Giving up.
0 passing (3m)
Command failed: karma start /mnt/c/Users/user/js-libp2p-keychain/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
Error: Command failed: karma start /mnt/c/Users/user/js-libp2p-keychain/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
at makeError (/mnt/c/Users/user/js-libp2p-keychain/node_modules/execa/index.js:174:9)
at Promise.all.then.arr (/mnt/c/Users/user/js-libp2p-keychain/node_modules/execa/index.js:278:16)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:118:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! …
```
> Adds no-sandbox to ChromeHeadless

- package.json
The bundlesize package wasn't updated for a while and is not compatible
with Node.js 12. Hence use a fork of it which is.
> fix: make AEGir Node.js 12 compatible

- src/checks/commitlint-travis.js
- src/config/eslintrc.js
Makes any function marked with the `async` keyword that does not include an `await` fail linting.
This is because the `async` keyword causes the marked function to be wrapped in a promise which creates a vm microtask which introduces a small amount of latency.  In hot codepaths this can add up to large amounts of wasted time.
Closes #354
> feat: require await in functions marked async

- src/lint.js
- test/lint.spec.js
In npm caret (^) and tilde (~) have the same meaning for versions
1.0.0 < x <= 0.1.0. Hence we can allow carat to be used for such
versions.
If you run `npm install <some-packages>` it automatically uses
caret for such versions. Hence you would need to manually update
your package.json to make it pass out linting. With this change
that's no longer needed.
Fixes #346.
> fix: allow development versions to use caret

- cli.js
- src/config/eslintrc.js
- src/docs/build.js
- src/error-handler.js
- src/lint.js
- src/test/index.js
- src/utils.js
Possibly contentious change.
Since we have the `debug` module, we generally don't need to use `console.log` and friends. It's useful during local debugging but it's also easy to forget to remove those lines so we could upgrade this to be an error to help ourselves out.
If you find that do need to use it (e.g. for cli output), you can easily disable the rule for that line with:
```javascript
console.info('Greetings Professor Falken') // eslint-disable-line no-console
```
> feat: change linting rules to make `console.foo` an error

- src/config/user.js
- test/config/user.spec.js
A common use of hooks in aegir is to start and stop an ipfs node for browser tests to run against.
Since they all use ipfsd-ctl and that is moving to async/await in ipfs/js-ipfsd-ctl#353 as part of ipfs/js-ipfs#1670, it would be nice to not have to mix async and callbacks in the hooks.
This PR adds support for async hooks while not breaking existing callback based ones.
> feat: support async hooks

- cmds/test.js
- src/test/node.js
The command for 100% test coverage in nyc is impossibly long. `tap` includes a `—100` option that simplifies this and so I’ve added the same here.
The command currently only applies to node tests until I figure out how to get coverage working in browser tests, but it is possible https://github.com/istanbuljs/puppeteer-to-istanbul
> feat: --100 for full coverage validation

- package.json
- src/docs/build.js
- src/test/node.js
Our previous theme was old and unmaintained, because of this  was causing docs generations errors and warnings
closes #369
> fix: use the default docs theme

- cli.js
- cmds/publish-rc.js
- cmds/update-last-successful-build.js
- src/publish-rc/index.js
- src/update-last-successful-build/index.js
- src/utils.js
This change adds two commands:
```console
aegir update-last-successful-build
```
This command updates a branch called `build/last-successful` (configurable)
It's intended to be run on CI after every successful build of master.
It:
1. Checks that it's running on the head (or detached head)  of `master`
1. Creates a temporary branch
1. Creates `yarn.lock` and `npm-shrinkwrap.json`
1. Adds them to git
1. Deletes the remote `build/last-successful` branch if it exists
1. Pushes the new `build/last-successful` to origin
It deletes the remote branch first because merging conflicts is tedious and
this branch should only be used by automated processes.
```console
aegir publish-rc
```
This creates a release branch for the next release and publishes a release candidate to npm.
It:
1. Deletes your …
> feat: add commands for publishing rc

- src/release/push.js
During the release process we push tags and the master branch. This only works if we're releasing from the master branch - if we're using a release branch we need to push that instead.
This PR pushes whatever branch we are currently on instead of only pushing master.
> fix: push to the current branch

- cmds/test-external.js
- cmds/update-rc.js
- cmds/update-release-branch-lockfiles.js
- package.json
- src/publish-rc/index.js
- src/test-external/index.js
- src/update-last-successful-build/index.js
- src/update-rc/index.js
- src/update-release-branch-lockfiles/index.js
- src/utils.js
Adds a command to test external/third party repos with a pre-release of js-ipfs.
1. Uses `connect-deps` to `npm link` the js-ipfs repo
2. Clones the target repo to a temp directory
3. Runs the tests of the target repo
4. Upgrades the target repo to use the pre-release of js-ipfs and
it's supporting `ipfs-http-client` version
5. Runs the tests again with the new version
If the repo doesn't depend on `js-ipfs` or `ipfs-http-client`, prints a warning an exits.
Handles monorepos too, treating each package as a separate target repo.
> feat: add test-external command

- cmds/publish-rc.js
- src/publish-rc/index.js
Default to creating rc branches with names like `release/v0.39.x` instead of just `v0.39.x`
This is so we can use regexes in `.travis.yml` to run certain extra checks on release branches like testing external repos without having to know the release branch name ahead of time.
> feat: prefix rc with release

- src/publish-rc/index.js
- src/update-rc/index.js
Since #426 was merged this shouldn't be necessary any more.
> fix: remove manual push after rc publish

- cmds/test.js
You can't use `-v` as a command alias as `yargs` thinks you mean `--version`.  You then can't use the long version either (e.g. `--verbose`) as `yargs` *still* thinks you mean `--version`.
```console
$ aegir test -t browser --verbose
20.4.0
```
```console
$ aegir test -t browser -v
20.4.0
```
Removing the `-v` alias makes `--verbose` work as expected.
> fix: force --verbose for verbose mode

- src/test-external/index.js
> Small improvement on top of #425 
This change detects presence of `yarn.lock` or `package-lock.json` in third-party repo and executes dependency install using optimized command speeding up the build made by `test-external` 
It also stops ipfs-companion from breaking js-ipfs release build if we go overboard with bleeding edge dependency overrides :^)
> feat: support lockfiles during text-external

- cmds/publish-rc.js
- cmds/update-last-successful-build.js
- cmds/update-rc.js
- cmds/update-release-branch-lockfiles.js
- src/publish-rc/index.js
- src/release/push.js
- src/update-last-successful-build/index.js
- src/update-rc/index.js
- src/update-release-branch-lockfiles/index.js
I have many different remotes becuase of checking out branches for external contributors. Git is confused because the branch exists on multiple remotes and fails with:
```
error: pathspec 'build/last-successful' did not match any file(s) known to git
hint: 'build/last-successful' matched more than one remote tracking branch.
```
This fixes that error.
> fix: specify remote for branch to checkout

- cmds/test.js
- package.json
- src/test/node.js
- test/fixtures/chai.js
- test/fixtures/tests/unhandled-promise-rejection.js
- test/test.spec.js
Adds a new flag to the test runner: `--no-unhandled-promise-rejections` which defaults to `true`.
When true this causes the `unhandled-rejections` node flag to be set to `strict` during the test run under node.
This means any `unhandledRejection` events raised on `process` will cause the process to exit and the tests to fail.
This is to ease our transition into the brave new world of mixing error handling strategies between async and event emitters.
Fixes #505
> feat: make unhandled promise rejections fail tests

- src/update-last-successful-build/index.js
- src/update-release-branch-lockfiles/index.js
`npm shrinkwrap` renames your `package-lock.json` if present, this includes project dev deps which npm [seems to be installing](https://github.com/ipfs/js-ipfs/issues/2774) even though the published module with the shrinkwrap file is a dependency.
If we install with the `--production` flag, then remove the `package-lock.json` file and *then* run shrinkwrap, no dev deps are included in the shrinkwrap file.
This only affects npm, yarn seems to do the right thing.
Fixes #516
> fix: remove package-lock before generating npm-shrinkwrap file

- cmds/release.js
- src/release/contributors.js
- src/release/index.js
- src/release/tag.js
Also splits commit/tagging into two separate commands and checks for file modifications before committing updated contributor lists.
> feat: allow enabling/disabling each part of the release process

- src/test/electron.js
To get stack traces out of electron-mocha we need to pass this flag.
See: https://github.com/jprichardson/electron-mocha/blob/master/lib/run.js#L166
> fix: pass --full-trace option to electron-mocha

- package.json
- src/config/karma.conf.js
- src/fixtures.browser.js
- src/fixtures.js
- src/test/electron.js
- src/utils.js
- test/browser.spec.js
This makes the served assets simpler and splits fixtures loading into node/browser files.
These changes make aegir works with karma and future browser runner `playwright-test`
lets try to stop electron from eager download the binaries 
prev:     Total disk usage: 302.3 MiB  Apparent size: 237.2 MiB  Items: 25368
now:      Total disk usage: 137.6 MiB  Apparent size:  75.4 MiB  Items: 25007
no-karma: Total disk usage: 135.0 MiB  Apparent size:  74.0 MiB  Items: 24441
> fix: fix webpack warn, make electron lazy

- src/config/karma.conf.js
- src/config/webpack.config.js
Do not put the users' whole env into the bundle, instead, just add the keys we want.
I don't know if we need other keys, but we definitely should not be including everything.
> fix: whitelist process env keys

- src/config/karma.conf.js
- src/config/webpack.config.js
They aren't massively useful as unless you are on the laptop of the person who published the build, all the paths are wrong.
Fixes #483, https://github.com/ipfs/js-ipfs/issues/3006
> feat: turn off sourcemaps for production builds

- cli.js
- cmds/build.js
- cmds/test.js
- src/config/webpack.config.js
This PR changes webpack config to not include node globals and built-ins by default.
Tracking issue here https://github.com/ipfs/js-ipfs/issues/2924
For now theres still a --node flag to allow node globals if needed.
`process` is still included because `readable-stream` will only remove it in v4 https://github.com/nodejs/readable-stream/pull/435
BREAKING CHANGE: browser code will NOT have node globals and builtins available.
> feat: default to not include node globals anf builtins

- cmds/build.js
The config for limiting the bundlesize is:
```js
{
bundlesize: {
maxSize: '100kB'
}
}
```
and not
```js
{
bundlesize: '100kB'
}
```
as the help text implies.
> fix: update bundlesize help command

- src/config/karma.conf.js
- src/test/browser.js
- src/test/electron.js
- src/test/node.js
The --invert flag requires `--grep` be used. This makes it easy to skip certain tests via the cli.
`npx aegir test --grep "test to skip" --invert`
> feat: add support for the mocha --invert flag

- src/config/eslintrc-js.js
- src/config/eslintrc-ts.js
- src/config/eslintrc.js
- src/lint.js
- test/fixtures/js+ts/package.json
- test/fixtures/js+ts/src/another.ts
- test/fixtures/js+ts/src/some.js
- test/fixtures/js+ts/src/typed.ts
- test/lint.js
Without this change `aegir` either uses esmodule parse rules or script based parse rules, which causes issues with repos that contain both `.ts` and `.js` files regardless of `--ts` option. Without `--ts` option it complains about `import` statements with `--ts` option it complains about use of unnecessary `'use strict'`.
This change introduces config for eslint that overrides based on file type using js config for js files and ts config for ts files. It also adds a test case which fails without this change.
Fixes https://github.com/ipfs/aegir/issues/618
> feat: Use file type based lint rules

- package.json
- src/test/electron.js
pin electron mocha to 9.3.0 to fix missing console.assert 
related:
https://github.com/jprichardson/electron-mocha/issues/173
> fix: fix electron timeout and renderer console.assert

- md/ts-jsdoc.md
I think we don't want to run whole `npm build` when dep is installed which does bunch of other things (that can fail).
> chore: prapare can just generate types

- src/build/index.js
So we can see bundle size output even if TS types fail.
> fix: build types after bundle size

- package.json
Just updates TS to 4.1.x which fixes type generation for generic class extensions
> feat: upgrade ts to 4.1.x

- src/ts/index.js
I'm not sure what was the reason to use relative path to the base config, but it brakes `"prepare": "aegir ts -p types` scripts when dep is coming from git url and package itself depends on `aegir` because it gets hoisted and base config isn't found.
This seems to resolve that issue.
> fix: prepare scripts when aegir gets hoisted

- cmds/build.js
- cmds/ts.js
- md/ts-jsdoc.md
- package.json
- src/build/index.js
- src/ts/index.js
- src/ts/typedoc-plugin.js
- support vendored types
- add --bundle and --types to the build cmd so we can disable either
- ts types preset doesn't overide `include` anymore just excludes the test folder
- ts types preset copies types folder to dist so it can be published
- ts docs preset reworked to use the types preset instead of having a custom config
- add docs about vendored types
> feat: support vendored types and improvements to build and ts cmds

- cli.js
- src/build/index.js
- src/config/user.js
- src/test/browser.js
- src/test/electron.js
- src/test/node.js
- src/ts/index.js
- we need to rename the flag to avoid conflicts in the options object with the `ts` cmd
- generate js files in TS repos
> feat: rename --ts flag to --ts-repo and fix ts repo support

- cli.js
- cmds/build.js
- cmds/ts.js
- package.json
- src/build/index.js
- src/config/user.js
- src/config/webpack.config.js
- src/docs/index.js
- src/lint.js
- src/release/bump.js
- src/release/commit.js
- src/release/contributors.js
- src/release/tag.js
- src/ts/index.js
- src/types.ts
- src/utils.js
- test/lint.js
- test/utils.js
Changes:
599252f (Hugo Dias, 7 minutes ago)
fix: add types for cmd options
923584d (Hugo Dias, 8 minutes ago)
feat: clean lint cmd
- remove old npm deps semver version checks
- update to the new eslint api
- use a new output formatter that actually gives us links we can click and
go to the errors
BREAKING CHANGE: old npm deps semver was removed
7a68ad1 (Hugo Dias, 10 minutes ago)
feat: big utils clean up
- remove unnecessary methods
- add some types
- improve `paths` export, with full paths to dist, test, src and
package.json folder/file
0a4cfc1 (Hugo Dias, 13 minutes ago)
fix: improve docs cmd
- add more types
- clean code and improve Listr setup
c6211a7 (Hugo Dias, 14 minutes ago)
feat: improve build cmd
- remove old bundlesize config, add new options for max bundlesize
`bundlesizeMax` …
> feat: ts, build, docs and lint improvements

- utils/fixtures.js
With latest releases the example is outdated
> docs: update fixtures path

- package.json
Otherwise resolution of the shared config fails during tsc compilation
without an explicit path to the file in your `node_modules` folder which
means the workflow of using gitpkg.now.sh to depend on monorepo packages
in PRs is completely broken if they have a prepare step or any other use
of typescript.
This is one solution, another would be to copy tsconfig.aegir.json to
the `dist` folder during a build, I have no opinion on which is better.
Refs: https://github.com/microsoft/TypeScript/issues/43245
> fix: add tsconfig.aegir.json to typesVersions

- package.json
- utils/chai.js
These are used by js-ipns so include them in order for it to just use
aegir for it's tests and not have extra chai modules hanging around.
> feat: add additional chai libraries

- utils/chai.js
If a chai extension has types they cannot be resolved by modules that depend
on aegir unless those types are in a definitely-typed-style `@types/chai-foo`
module.
This seems to be because we don't export them from the `utils/chai.js`
file so they are not referenced from anywhere, then when we try to use
chai with the extensions from another module their types have not been
loaded so chai's base types are not extended and we have missing methods
everywhere. Unless of course, they are in a `@types/...` module in which case
typescript's default module resolution algorithm will find them, though more
by accident than by design.
Here we export the chai extensions, ensuring their types will be loaded
by the generated `.d.ts` file, then delete the exported property as we don't
really want to …
> fix: export types for chai extensions

- package.json
It's a runtime dep of dependant modules so needs to be in the dependencies field.
> chore: move chai-string to deps

- src/config/user.js
Enables linting of typescript definition files to ensure correct and consistent syntax.
Refs: #849
BREAKING CHANGE: what was not previously linted will now be linted so it may surface new errors
> feat: lint .d.ts files

- src/cmds/lint.js
- src/cmds/test.js
- src/cmds/ts.js
- src/cmds/z-dependency-check.js
`'array'` is not a valid value for `'type'` so we can remove the `@ts-ignore` that was smothering the error message telling us so.
> fix: replace type: 'array' with array: true

- actions/bundle-size/Dockerfile
Docker actions get their workspace overridden as `/docker/workspace`.  Your project files are copied to that folder \*after* your docker file is run but \*before* the `CMD` directive is executed, so you can't copy anything to that folder and expect it to still be there.
The contents of `/docker/workspace` are the project, not the gh action, so `dist/index.js` does not exist.
We don't ship gh actions with aegir so you can't use `/docker/workspace/node_modules/aegir/actions/bundle-size/dist/index.js` either.
Also, you can't use slashes in branch names for gh actions as they get copied onto the filesystem then the directory structure doesn't match up.
The working directory of the docker image is `/docker/workspace` so we can copy the bundle size index.js to the root and run it from there but …
> chore: copy bundle-size to root

- src/config/user.js
In esm projects, sometimes `.aegir.js` is called `.aegir.cjs`
> fix: search for aegir.cjs

- utils/fixtures.js
We need to be able to load fixture files from modules like `interface-ipfs-core`.
As these modules transition to ESM, they define their export maps but
IPJS needs these to only contain js files so we can't use it for fixtures
though that gets unwieldy quite quickly anyway.
Instead simulate node's node_modules lookup, stepping up the file system
path searching every folder called node_modules if it exists.
> fix: simulate node_modules lookup when loading fixtures

- utils/fixtures.js
- utils/resolve.js
The ESM `import.meta.url` value does not work reliably in environments
like electron just yet so add a resolve command to let us work out
paths to files in dependencies.
> feat: add resolve command

- src/cmds/test-dependant.js
- src/test-dependant/index.js
- test/dependants.js
- test/fixtures/test-dependant/monorepo/packages/submodule/package.json
- test/fixtures/test-dependant/project/package.json
- Adds an option to test dependent to choose the script to run (default -> test)
> feat: add option to choose the script to run to test dependent

- src/cmds/test-dependant.js
- src/test-dependant/index.js
- test/dependants.js
Print an error message and exit with a non-zero code when testing dependants fails
> fix: exit with an error when testing dependants fails

- package.json
- src/test/node.js
If your tests are written in ts, you need to include `source-map-support` in order to get stack traces that point to the ts code, otherwise they point to the transpiled code which is a pain to deal with.
Also fixes the recent breakage with dep checking - looks like they stopped bundling the `detective` module, so I've switched it for `detective-cjs` since that's what's now used in the dependency-check module tests.
> feat: support source maps for ts

- src/docs/index.js
There's a conflict between the `noEmit` and `emitDeclarationOnly` config
directives that causes typedoc to bail.
Read the users' config and remove the conflict before generating docs.
Fixes #881
> fix: doc generation

- package.json
- utils/chai.js
Chai-checkmark doesn't work well with promise based flow control as it requires a `done` function and mocha objects to the use of both `done` and `async` in test function signatures.
Probably better to just use await instead.  As a bonus it also makes the logic in a test easier to follow.
> chore: remove chai-checkmark

- package.json
To fix bugs like https://github.com/ipfs/js-ipfs/issues/3938 where Jest ends up resolving browser specific code, use a version of ipjs with the fix.
> chore: demand up to date ipjs

- package.json
- test/test.js
- utils/chai.js
Swaps `chai-bytes` for `chai-bites` as we can write tests that are less verbose.
> chore: swap chai-bytes for chai-bites

- src/build/index.js
forward args are now being passed to `tsCmd` via the `ctx` object in the 'Generate types' task
fixes #940
> fix: tsc receives forward args

- package.json
- src/cmds/dependency-check.js
- src/config/user.js
- src/dependency-check.js
- src/lint.js
- src/test/electron.js
- src/test/node.js
- src/utils.js
- utils/chai.js
Removes esbuild-register as it tries to load modules via cjs paths which break with esm.
Ts-node doesn't seem to work either so for now we have to build before running tests.
> fix: remove ora and use listr instead, make tests run on node

- package.json
@semantic-release/github doesn't respect GitHub's rate limiting - it
did once but it looks like GH changed their response type and now it doesn't
which means publishing large monorepos like `@libp2p/interfaces` is a dice
roll as to whether it will succeed or not.
Here we switch to a temporary fork that uses the `@octokit` plugins
for throttling and retrying so it should be more reliable.
Refs: https://github.com/semantic-release/semantic-release/issues/2204
> fix: use @semantic-release/github fork

- src/lint.js
If a project is ts, there's no need to run tsc during linting as we will have done it during building.
We only want to run tsc for typed esm/cjs projects.
> fix: skip tsc during linting for ts projects

- src/test/browser.js
- src/test/index.js
- src/test/react-native.js
- test/test.js
- tsconfig-check.aegir.json
Since esbuild is run over browser tests, we want to pass the uncompiled versions to the test runner, otherwise esbuild doesn't match the browser overrides from the project's package.json.
> fix: run uncompiled tests for browsers

- src/build/index.js
- src/test/browser.js
- src/test/index.js
In order to not have to declare browser overrides for both `src` and `dist`, run tests on the compiled test output for ts projects.
> fix: run compiled tests

- package.json
- tsconfig-check.aegir.json
- utils/resolve.browser.js
Resolve requires use of node features so add browser overrides to ensure it's not pulled in during bundling.
> fix: make resolve node-only

- src/cmds/dependency-check.js
- src/config/user.js
- src/dependency-check.js
Run dep check command twice - once to check all deps of a project are
present and once again to only check production code for production
deps in order to catch the instance when we add a production dep to
the dev deps list.
> fix: run dep check in prod mode

- src/index.js
Import all of the exported types in the index file so the types from this module are actually useable.
> fix: export types

- package.json
For some reason in my dep tree, npm always resolves lilconfig@2.0.4 which has bug with async loading (fixed in 2.0.5: https://github.com/antonk52/lilconfig/commit/0f68c45a9c4c763131117dc86b537349434e2299). 
That bug surfaces in libp2p with the following error:
```
TypeError: `[object Promise]` is not an Option Object
at module.exports (libp2p/js-libp2p/node_modules/merge-options/index.js:164:10)
at config (libp2p/js-libp2p/node_modules/aegir/src/config/user.js:168:39)
at async main (libp2p/js-libp2p/node_modules/aegir/src/index.js:35:22)
```
After I forced 2.0.5 version, npm resolves correct version but this will ensure nobody resolves buggy version
> chore: update lilconfig version in package.json

- test/test.js
Using `npm link` ends up deleting folders called "build" from the node_modules folder which is undesirable.
Instead just create the `.bin` directory and symlink aegir into it for testing.
> fix: ts tests

- src/config/user.js
Add ignores for files like `index.min.js` and any fixtures in the dist folder when checking dependencies.
> fix: ignore minified files and transpiled fixtures in dep-check

- src/check-project/manifests/typed-esm.js
- src/check-project/manifests/typescript.js
- src/check-project/utils.js
Make sure types field is first in the exports map for TypeScript 4.7
> fix: sort exports map

- src/config/user.js
Ignore aegir not being used in code as we're using it to run the dep-check so, uh, it is used.
> fix: ignore aegir during dep-check

- src/check-project/index.js
- src/check-project/utils.js
- src/cmds/release.js
- src/config/user.js
- src/release.js
- src/types.ts
We use `semantic-release-monorepo` to publish packages in monorepos.
We use `lerna` to work out sibling cross-dependencies to ensure we publish in the correct order.
This all seems to work ok, but `semantic-release-monorepo` doesn't update dependency versions for cross-dependent siblings when they change.
We can lean on semver ranges to take care of this for the most part but it breaks when we release a major version of a sibling.  In this case the other siblings have been coded against the new API but still depend on the old version which breaks.
This pr adds a job to the release command that, if we are a monorepo, synchronises the versions of all sibling dependencies after each publish.
> feat: align monorepo sibling versions

- src/config/user.js
- src/test/index.js
We run build before test but pass `--no-bundle` on the assumption that a project build command is `aegir build`.  Passing `--no-bundle` skips making a minified build for a tiny speedup.
If the project build command isn't `aegir build` this can break things so remove the optimisation.
Also build by default before test (to support typescript) and fix the problem whereby the build flag was being ignored for typescript projects.
Fixes: #975
> fix: remove no-bundle from test build and fix flag

- src/check-project/files/lerna.json
lerna supports parsing workspace path defs from `package.json` so use that in order to silence the warning you otherwise see.
> feat: tell lerna to use npm workspaces

- src/check-project/check-licence-files.js
- src/check-project/check-monorepo-files.js
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/files/lerna.json
- src/check-project/index.js
- src/check-project/readme/structure.js
- src/check-project/utils.js
Also print useful error messages when parsing a file as JSON fails (e.g. print out which file)
> fix: preserve readme definitions when checking project config

- src/check-project/index.js
> fix: check-project uses correct projectDir

- src/check-project/utils.js
- src/cmds/check-project.js
Because we merge an object with the `"."` style export, ignore any single-export style fields.
> fix: ignore single-import from exports map

- README.md
- md/github-actions.md
- md/ts-jsdoc.md
The `aegir ts` command has been removed in favour of doing everything during `aegir build` so remove the references to it in the docs.
closes #1077
> docs: remove ts command docs

- src/check-project/readme/header.js
Use repoOwner/repoName instead of hard coded (incorrect) repo owner/name
> fix: fix ci link for libp2p repos

- src/config/user.js
Use the CI env var to default publishing docs to true when running in CI.
> fix: publish docs by default in CI

- src/check-project/readme/install.js
If a module declares test scripts for browsers, add a block to the readme that details how to use browser script tags.
> fix: only add browser script tag instructions for browser modules

- src/check-project/check-monorepo-readme.js
- src/config/user.js
- src/release.js
- src/utils.js
- test/docs.js
CI has `NODE_ENV=test` so docs release is skipped, control publish setting from release job instead.
> fix: generate docs on publish, control publishing from release job

- src/check-project/check-monorepo-files.js
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/files/npmrc
- src/docs.js
nx trips over the tarball dep we have on `@semantic-release/github` when it tries to parse project deps from the `package-lock.json` in CI so disable lockfiles in monorepos.
This will no longer be necessary when https://github.com/semantic-release/github/pull/487 is merged.
> fix: disable package-lock.json in monorepos

- src/docs/type-indexer-plugin.cjs
- test/docs.js
- test/fixtures/projects/a-monorepo/package.json
- test/fixtures/projects/a-monorepo/packages/a-workspace-project/package.json
- test/fixtures/projects/a-monorepo/packages/a-workspace-project/src/index.js
- test/fixtures/projects/a-monorepo/packages/a-workspace-project/src/types.ts
- test/fixtures/projects/a-monorepo/packages/a-workspace-project/tsconfig.json
- test/fixtures/projects/a-monorepo/packages/another-workspace-project/package.json
- test/fixtures/projects/a-monorepo/packages/another-workspace-project/src/index.js
- test/fixtures/projects/a-monorepo/packages/another-workspace-project/src/types.ts
- test/fixtures/projects/a-monorepo/packages/another-workspace-project/tsconfig.json
In a monorepo sometimes the packages folder name is prepended to the url mapping source file name and sometimes it isn't so ignore that and just use the absolute path to determine the package.json for a given file.
> fix: only use absolute path of url mapping to find project context

- src/check-project/check-readme.js
- src/check-project/index.js
- src/check-project/readme/api-docs.js
Link directly to the module pages of monorepo child project api docs.
> fix: link to api docs from monorepo child projects

- .gitignore
- package.json
- src/docs.js
- test/docs.js
- test/fixtures/projects/a-ts-project/src/a-module.ts
- test/fixtures/projects/a-ts-project/src/index.ts
- test/fixtures/projects/an-esm-project/src/index.js
- test/fixtures/projects/an-esm-project/src/types.ts
Closes https://github.com/ipfs/aegir/issues/1130
> fix: Added support for generating docs for referenced types 

- src/docs.js
- src/docs/type-indexer-plugin.cjs
- src/docs/unknown-symbol-resolver-plugin.cjs
- test/docs.js
- test/fixtures/projects/a-ts-project/src/index.ts
To avoid generating docs for `@types/node` and typescript internals,
exclude documenting types from `node_modules`.
> fix: exclude node_modules from docs

- src/cmds/exec.js
- src/cmds/run.js
- src/config/user.js
- src/exec.js
- src/index.js
- src/run.js
- src/types.ts
- src/utils.js
The only reason we keep lerna about is for running scripts and commands in monorepo packages.  Unlike npm it's clever enough to figure out the dependency graph of monorepo packages before running the commands or scripts in order to ensure that they've been run in a modules dependencies before being run in that module.
This PR adds two new commands to aegir that do the same thing:
1. exec - this will run a binary command in each monorepo package
2. run - this will run one or more npm scripts in each package
E.g. run `ls` in every package
```console
$ aegir exec ls
```
E.g. clean and build every package
```console
$ aegir run clean build
```
Both commands support forwarding args:
E.g. lint every package, fixing errors
```console
$ aegir run lint -- --fix
```
> feat: add run and exec commands for executing commands in monorepo packages

- src/lint.js
To make the output of eslint a bit eaier to read, print the errors in red.
> fix: print linting errors in red

- src/check-project/check-monorepo-files.js
- src/check-project/files/npmrc
We had an npmrc to work around a bug in lerna.  Now that lerna can be removed from monorepos we don't need to create the npmrc any more.
> fix: do not create npmrc for monorepos

- package.json
- src/env.js
We frequently want to only run certain tests in certain environments so we include `wherearewe`, `detect-node`, `is-electron` and other modules.
Ship a `/env` entrypoint to reduce the redundancy:
```js
import { isNode } from 'aegir/env'
if (isNode) {
// do node things
}
```
> feat: add env

- package.json
- src/cmds/release-rc.js
- src/config/user.js
- src/index.js
- src/release-rc.js
- src/types.ts
The last thing we use lerna for is releasing RC versions of monorepo packages, so add a command here that does the same thing.
It adds the git hash to the version number, updates sibling dependencies to that new version number then publishes the packages all in the order of dependency.
> feat: add release-rc command

- actions/cache-node-modules/action.yml
I've used this action several times and did not know that it was also calling `npm run build`. 
The build step can increase a workflow's runtime and complexity, and I usually don't want to do that. I think it's useful, but since there was already support for `inputs.build`, I think it's unnecessary. An opt-out (since we don't want to break existing users) will help me out a lot.
> feat: build opt-out for cache-node-modules action

- actions/cache-node-modules/action.yml
Update actions/cache to v3 to use node 16 instead of node 12 which is now deprecated by GitHub.
> fix: update actions/cache

- src/docs/type-indexer-plugin.cjs
- test/docs.js
- test/fixtures/projects/a-ts-project/src/index.ts
When generating the typedoc index for a module, include enums.
> fix: include enums in typedoc index

- package.json
TypeScript used to be able to resolve the extends field in `tsconfig.json` using the node require algorithm.
Recent versions of TypeScript have a regression that means that if a module has an exports map, the extendable typescript config file has to be in that exports map so add it here.
Refs: https://github.com/microsoft/TypeScript/issues/53314
> fix: add tsconfig to exports map

- src/check-project/utils.js
- src/config/.npmpackagejsonlintrc.json
The engines field causes warnings on npm but errors on yarn when the required node version is not met.
Not all of our modules require LTS node and they are used by projects outside of libp2p/helia/etc.
This change removes the automatic addition of an engines field to a project's `package.json` while running the `check-project` command, instead projects that do require a certain node version are free to define it and deal with the breakage that subsequently occurs.
Partial revert of: #1184
Closes: https://github.com/ipfs/aegir/issues/1276
> fix: do not enforce engines in package.json

- src/check-project/check-licence-files.js
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/cmds/lint-package-json.js
- src/cmds/lint.js
- test/fixtures/dependency-check/pass/index.js
- test/fixtures/js+ts/src/some.js
- test/fixtures/tests/context-access.js
- test/utils/get-port.js
[This commit](https://github.com/standard/eslint-config-standard/commit/9673e0bb5a04d0d4b04333e33731514210a16664) to `eslint-config-standard` altered the `no-multiple-empty-lines` rule so update to the new linting rules.
> chore: fix linting

- src/check-project/index.js
- src/utils.js
Test that workspace entries are directories and have package.json files before processing them.
> fix: handle invalid workspace entries

- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/index.js
- src/check-project/manifests/untyped-esm.js
- src/check-project/readme/header.js
Not all projects use js-test-and-release.yml as their main CI file so allow specifying something different.
> fix: allow specifying ci file in check-project

- src/check-project/readme/api-docs.js
If a package is in a monorepo and it has no typedoc entry point no API doc link should be generated.
> fix: when generating api doc link, check typedoc entry point

- src/test/browser.js
Autodetecting test runners is broken in playwright test. We only use mocha so just pass it in as an option.
Refs:
- https://github.com/hugomrdias/playwright-test/issues/573
- https://github.com/hugomrdias/playwright-test/issues/572
> fix: hard code mocha runner for pw-test

- src/config/user.js
This is done after a release so make it a chore to prevent it causing release-please to create a new release.
> fix: make updating sibling deps a chore

- src/check-project/readme/api-docs.js
When building docs for monorepos, the typedoc manifest key is no longer used so just check for docs in the root.
> fix: check monorepo root for docs

- package.json
- src/types.ts
- test/fixtures/projects/a-monorepo/packages/a-workspace-project/src/types.ts
- test/fixtures/projects/a-monorepo/packages/another-workspace-project/src/types.ts
- test/fixtures/projects/a-ts-project/src/a-module.ts
- test/fixtures/projects/a-ts-project/src/index.ts
- test/fixtures/projects/an-esm-project/src/types.ts
- See https://github.com/ipfs/eslint-config-ipfs/pull/190
BREAKING CHANGE: All interfaces now need to use method signature style rather than property function style
eg:
before
```ts
interface Foo {
bar: (baz: number) => void
}
```
after
```ts
interface Foo {
bar(baz: number): void
}
```
> deps!: update eslint-config-ipfs

- CHANGELOG.md
The ts doc checker does not like having the same interface in a file with the same method names.
Quick fix for https://github.com/bbc/typescript-docs-verifier/issues/30
> chore: fix linting errors

- src/check-project/manifests/typed-cjs.js
- src/check-project/manifests/typed-esm.js
- src/check-project/manifests/typescript.js
- src/check-project/manifests/untyped-cjs.js
- src/check-project/manifests/untyped-esm.js
To support linting a file using the nearest config add `package: true`
to the default parser options.
> fix: add package to eslint parser options

- src/cmds/exec.js
- src/cmds/run.js
- noticed some likely leftover copy pasta 
- fix `run --bail` and `exec --bail` defaults
> fix: set bail defaults correctly

- src/cmds/test.js
This is not fixed, it's still causing larger builds to hang.
Reverts ipfs/aegir#1195
> fix: disable test coverage again

- src/cmds/test-dependant.js
Scoped deps have multiple `@` symbols in the version override string so we need to handle that.
> fix: handle scoped deps in test-dependant

- src/check-project/check-build-files.js
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/index.js
- src/check-project/readme/header.js
Recognises the helia header image for readmes, etc
> fix: support helia projecs in check-project

- actions/cache-node-modules/action.yml
Fixes a regression introduced by #1070.
Essentially you can't include `${{ ... }}` inside regular YAML `if` clauses, you have to have the whole clause inside `${{ ... }}`.
This explains why every monorepo job builds on every run despite the npm/build cache being hit.
For the situation where the build cache exists (run GH action with debug logging turned on to see this sort of thing):
Before:
```
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: (success() && format('steps.cache.outputs.cache-hit != ''true'' && {0} == ''true''', inputs.build_on_cache_fail))
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating format:
##[debug]....Evaluating String:
##[debug]....=> 'steps.cache.outputs.cache-hit != ''true'' && {0} == ''true''' …
```
> fix: do not run `npm --if-present build` on npm cache hit

- README.md
- package.json
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/files/gitignore
- src/check-project/readme/header.js
- src/check-project/readme/install.js
- src/check-project/readme/structure.js
- src/docs.js
- src/docs/readme-updater-plugin.js
- src/utils.js
Adds a typedoc plugin to extract module comments (e.g. `@packageDocumentation`) and add them to the README in an `About` section when `npm run docs` is run.
It will also keep them in sync using the source code as a source of truth.
> feat: sync packageDocumentation between index.ts and README.md

- src/docs.js
Large projects can cause OOMs so increase default ram to reduce config duplication.
> fix: increase doc ram

- src/docs/readme-updater-plugin.js
Otherwise comma+spaces are inserted as the default join character.
> fix: join readme example descriptions with ''

- src/check-project/readme/api-docs.js
- src/check-project/readme/install.js
- src/check-project/readme/license.js
- src/check-project/readme/structure.js
- src/docs/readme-updater-plugin.js
If there's no package name we need a h1 otherwise some ToC generators generate weird output.
Bump all existing headers by one level.
> fix: increase header level for readme items

- src/cmds/test.js
- src/config/user.js
- src/test/node.js
- src/types.ts
Watch for test output that looks like the end of a successful test run - if collecting coverage takes too long, kill the process but do not cause the test run to fail.
Temporary workaround for https://github.com/ipfs/aegir/issues/1206
> fix: if a test run looks like it's hung during coverage, kill it

- src/docs/readme-updater-plugin.js
TypeDoc was updated recently to parse the example title correctly so use if it is available
> fix: use example title if it is available

- src/cmds/docs.js
- src/docs.js
- src/types.ts
Expose the `cname` option from `gh-pages` to support publishing docs on a custom domain.
> feat: support cname for docs publishing

- src/build/index.js
It's prettier and works better.
> fix: point to esbuild bundle analysis tool instead of bundlebuddy

- src/check-project/check-licence-files.js
- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/check-typedoc-files.js
- src/check-project/index.js
- src/check-project/manifests/typescript.js
- src/check-project/utils.js
- src/utils.js
Release-please updates sibling deps to the latest patch release so don't clobber those changes when running `npx aegir check-project`.
Also skip adding release config to modules that have `"private": true` in their `package.json`.
> fix: update check-config command to handle release-please monorepos

- package.json
resolves multiple errors of error TS2307: Cannot find module 'mdast' or its corresponding type declarations.
> fix: add missing @types/mdast dep

- package.json
- src/check-project/index.js
To ensure people with lockfiles get the latest version of deps, update patch versions during `check-project`.
> fix: update patch deps during check-project

- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/index.js
- src/check-project/manifests/monorepo.js
- src/check-project/readme/header.js
- src/docs/readme-updater-plugin.js
To prevent people opening PRs that update READMEs when they will be generated, add a comment to the README pointing people in the right direction.
> fix: add note to readmes about editing index.ts instead

- actions/cache-node-modules/action.yml
Updates to [actions/cache@v4](https://github.com/actions/cache/releases/tag/v4.0.0) which among other things uses Node.js 20 so silences all the warnings about Node.js 16 still being used.
> fix: update to actions/cache@v4

- src/check-project/check-monorepo-readme.js
- src/check-project/check-readme.js
- src/check-project/index.js
- src/check-project/readme/license.js
To prevent broken links in api docs, use absolute links in generated readme files.
> fix: use absolute links in generated readme

- package.json
- src/check-project/index.js
- src/release.js
- src/test-dependant/index.js
- src/utils.js
It takes about 30 seconds for the `glob` stuff to run any command in my project. This PR fixes that
> fix: use fast-glob for resolving projects

- src/docs/readme-updater-plugin.js
Workaround for https://github.com/syntax-tree/mdast-util-to-markdown/issues/61
> fix: do not escape GitHub alerts in readmes

- src/align-versions.js
- src/check-project/check-monorepo-readme.js
- src/check-project/index.js
- src/check-project/manifests/monorepo.js
- src/check-project/manifests/typed-cjs.js
- src/check-project/manifests/typed-esm.js
- src/check-project/manifests/typescript.js
- src/check-project/manifests/untyped-cjs.js
- src/check-project/manifests/untyped-esm.js
- src/check-project/readme/structure.js
- src/utils.js
Updates default config for semantic-release-monorepo
> fix: update check-project to use semantic-release-monorepo again

- package.json
Fixes the breakage from the latest commit analyzer release.
Refs: https://github.com/semantic-release/release-notes-generator/issues/633
> fix: use semantic-release beta release

- package.json
The latest `eslint-plugin-jsdoc` broke rule resolution, pin until https://github.com/gajus/eslint-plugin-jsdoc/issues/1277 is fixed.
> fix: pin eslint-plugin-jsdoc

- package.json
- src/config/tsconfig.aegir.json
- test/fixtures/dependency-check/fail-unused/index.js
- test/fixtures/dependency-check/ts-fail/src/index.ts
- test/fixtures/dependency-check/ts-pass/src/index.ts
- Resolves https://github.com/ipfs/aegir/issues/1459
- Since all relevant typescript linter rules are now incorporated in the latest eslint-config-ipfs, we can drop them from our tsconfig.
> feat: move tsc linter rules to eslint

- src/dependency-check.js
- test/dependency-check.js
- test/fixtures/dependency-check/jsx-fail/package.json
- test/fixtures/dependency-check/jsx-fail/src/index.jsx
- test/fixtures/dependency-check/jsx-pass/package.json
- test/fixtures/dependency-check/jsx-pass/src/index.jsx
- test/fixtures/dependency-check/tsx-fail/package.json
- test/fixtures/dependency-check/tsx-fail/src/index.tsx
- test/fixtures/dependency-check/tsx-pass/package.json
- test/fixtures/dependency-check/tsx-pass/src/index.tsx
- tsconfig.json
Adds configuration to dependency-check command to check for unused dependencies properly in jsx & tsx files.
Also adds tests
> fix!: dep-check tsx and jsx

- package.json
Playwright-core is breaking all chrome testing after the `1.49.0` release so override the resolved version to `1.48.0`.
This can be reverted after https://github.com/hugomrdias/playwright-test/pull/685 is merged.
> fix: override playwright core version

- src/build/index.js
- src/document-check.js
- test/fixtures/document-check/pass/GOODREADME.md
Sometimes we want to show examples that use modules that aren't a dependency of the module we are documenting.
In this case tsc throws `TS2307` when trying to compile the example code block.
Ignore this error so we can just treat these deps as `any` while still getting the benefit of compiling the rest of the code block.
> fix: ignore module-not-found errors in doc-check

- package.json
- test/utils/echo-server.js
`fetch` is global in node so remove the undici dep.
> chore: remove undici

- src/config/tsconfig.aegir.json
Turn on `allowImportingTsExtensions` to allow importing `.ts` files.
This is a prequisite of using Node.js type stripping in v24 (may be backported to v22).
Refs: https://github.com/libp2p/js-libp2p/issues/2812
> fix: allow importing .ts files

- package.json
Uint8Arrays are hopelessly broken in recent versions due to them being made generic so pin the version until this mess is sorted out.
Ref: https://github.com/microsoft/TypeScript/issues/61793
> fix: pin typescript
