ipfs/aegir

bin/build
bin/release
tasks/release/browser.js
tasks/release/node.js
tasks/release/post-build.js
tasks/release/pre-build.js

An attempt on #5. Tested both release and build and everything seems fine. Let me know if the tasks structure makes sense this way or not.

Add support for dignified-release node/browser

---

README.md
bin/release
tasks/release.js
tasks/release/bump.js
tasks/release/default.js
tasks/release/no-build.js
tasks/release/node.js
tasks/release/post-build.js

fix: Better env specific tasks

---

config/karma.conf.js
config/webpack.js
package.json
tasks/build/browser.js
tasks/coverage.js
tasks/test/node.js

this also adds umd definitions and source maps for the browser build

fix: minify the index.min file

---

README.md

@dignifiedquire: are these accurate? I was using aegir today and was thinking about what things users would want to know aegir does/doesn't require. Let me know if I've misunderstood and some of these aren't necessary.

Update README with stack deps

---

config/eslintrc.yml

fixes https://github.com/dignifiedquire/aegir/issues/56

add curly rule

---

config/intro-template.md.js
tasks/docs/build.js

Ref: https://github.com/ipfs/js-ipfs/issues/615#issuecomment-266401035
Preview: https://multiformats.github.io/js-multibase/

feat(docs): add generic intro template

---

package.json

Closes #105
https://greenkeeper.io/

fix(package): update webpack-merge to version 4.0.0

---

package.json

Closes #106
https://greenkeeper.io/

fix(package): update gulp-mocha to version 4.1.0

---

src/release/index.js

fix(release): correctly run tests on release

---

src/config/webpack/index.js

This fixes the builds on Windows machines.

fix: use relative paths on windows

---

package.json
src/config/karma.conf.js

fix: process.env inacessible in browser tests

---

.travis.yml
package.json
src/config/karma.conf.js
src/config/webpack/index.js
src/test/browser-config.js
src/test/browser.js
src/utils.js
test/browser.spec.js
test/lint.spec.js

Original plugin broke on webworkers. Now enabled browser and webworker tests on ci as well implemented the correct fix for it

fix(test): inject missing webpack config into tests

---

package.json

With putting pre-push targets like:
"pre-push": [
"lint",
"test"
]
into your package.json, those will run before pushing.

feat: run pre-push targets if there are any

---

src/fixtures.js
test/browser.spec.js

It was failing silently before.

fix: throw an error if fixture is not found

---

README.md
package.json

for https://github.com/ipfs/community/pull/301

add lead maintainer

---

src/fixtures.js

fix: restores previous behaviour for loading browser fixtures

---

README.md

See https://github.com/ipfs/aegir/issues/238#issuecomment-398387625 for context

docs: document AEGIR_GHTOKEN env var

---

src/utils.js

I just lost about 30 minutes trying to track down why AEgir wasn't running my hooks.

fix: do not smother user config parse error

---

src/build/index.js
src/release/index.js

fix: build not run during release cmd

---

cmds/z-dependency-check.js

example of an use case https://github.com/ipfs/interface-js-ipfs-core/pull/441

feat: exclude fixtures from dep-check

---

src/config/karma.conf.js

@vmx does this fix your issue in ipfs-bitswap ?

fix: use the same timeout for mocha and karma-mocha

---

cmds/test.js
package.json
src/test/electron.js
src/test/index.js

this PR adds electron targets
- electron (main process)
- electron-renderer (renderer process)

feat: add support for electron in tests

---

src/config/babelrc.js
src/config/webpack.config.js
src/utils.js

fixes #379 fixes #380 fixes #381

fix: use default babel config and update browserslist

---

cmds/update-rc.js
src/update-rc/index.js

Follows on from #419, just used to publish https://www.npmjs.com/package/ipfs/v/0.38.0-rc.1

feat: adds command to update release candidates

---

package.json
src/fixtures.js

fix: fix electron detection

---

package.json
test/utils/echo-server.js
utils/echo-server.js

To be able to verify in tests that we send the correct headers

feat: echo request headers

---

src/config/karma.conf.js

This PR replaces the plugins from the main webpack config with the plugins specific for tests.

fix: fix process.env in karma tests

---

package.json

typedoc doesnt support 4.1 yet

fix: pin ts to 4.0.x

---

md/ts-jsdoc.md

We notice that the `typesVersions` workaround makes TS rewrite `import('cids')` to `import('cids/src')`, so a solution is added to the config.
This also rewrite the text a bit to explain that `typeVersions` should only be used if its really needed and not by default.
closes #703

docs: typesVersions workaround

---

actions/bundle-size/dist/index.js
actions/bundle-size/utils.js

When using bundle size github action. Action uploads bundle to github artifacts ans uses package name as artifact name. Unfortunately when you add this action to namespaced package, like '@chainsafe/libp2p-noise', action fails because "/" is illegal character for github artifact name.

fix: uploading bundlesize artifact uses invalid character with namespaced modules

---

package.json
utils/chai.js

This extension is used in the libp2p-interface compliance tests

feat: add chai-checkmark

---

src/config/tsconfig.aegir.json

fix: configure source maps

---

cli.js
package.json
src/test/react-native.js
test/lint.js

BREAKING CHANGE: new typescript minor, caught errors have changed type among other things

chore: update typescript

---

package.json
src/release/commit.js
src/release/contributors.js
src/release/push.js
src/release/tag.js

- ran `npm test`
- ran `npm src/index.js release --commit`

chore(deps): bump simple-git from 2.37.0 to 3.3.0

---

src/check-project/check-monorepo-files.js
src/check-project/manifests/typed-cjs.js
src/check-project/manifests/typed-esm.js
src/check-project/manifests/typescript.js
src/check-project/manifests/untyped-cjs.js
src/check-project/utils.js

If the release script uses aegir or semantic release make sure the config is correct.

fix: set correct semantic-release config for files with aegir release

---

src/dependency-check.js

fix: dep-check command name

---

src/check-project/check-monorepo-readme.js
src/check-project/index.js
src/check-project/readme/header.js
src/check-project/readme/install.js
src/check-project/readme/license.js
src/check-project/readme/structure.js
src/check-project/readme/utils.js

Standardises the main readme for monorepo projects

feat: parse monorepo project readme

---

src/check-project/readme/header.js

Use configured org and repo name for ci link.

fix: correct default repo name and org in header

---

.github/dependabot.yml
package.json
src/check-project/semantic-release-config.js

Also chores should not trigger a release.

fix: make revving deps trigger a release

---

src/check-project/readme/header.js

https://github.com/ipfs/js-ipns/pull/180#discussion_r972826024

fix: update readme badges

---

package.json
src/check-project/check-licence-files.js
src/check-project/utils.js

fix: add missing deps

---

README.md
src/check-project/readme/header.js

Shields made a breaking change so unbreak it.
Refs https://github.com/badges/shields/issues/8671

fix: update ci badge link

---

src/env.js

docs: document env export

---

src/check-project/check-build-files.js
src/check-project/files/gitignore
src/check-project/index.js

Also enforce gitignore contents

fix: update default branch pattern detection

---

src/config/tsconfig.aegir.json

see https://github.com/libp2p/js-libp2p-webtransport/pull/59\#discussion_r1145871872

fix: use WebWorker lib in tsconfig

---

.aegir.js
package.json
src/dependency-check.js
test/dependency-check.js
test/fixtures/dependency-check/esm-pass/src/other.cjs
test/fixtures/dependency-check/fail-unused/index.js
test/fixtures/dependency-check/fail-unused/package.json
test/fixtures/dependency-check/ts-pass/src/other.ts

Format the dep-check error message to make it easier to read.

fix: print useful dep-check message

---

src/cmds/lint.js

fix: update eslint repo url

---

.github/workflows/semantic-pull-request.yml
.gitignore
package.json
src/check-project/check-build-files.js
src/check-project/files/.github/workflows/semantic-pull-request.yml
src/check-project/files/.github/workflows/stale.yml
src/check-project/files/gitignore
src/check-project/utils.js

Add extra file checks to check-project command

fix: include stale and pr check workflows

---

src/config/tsconfig.aegir.json

This allows `Array.toSorted`, among other things.

fix: use ES2023.Array

---

src/utils.js

This method needs to be sync otherwise readme updating during doc generation breaks.

fix: use sync glob

---

package.json

https://github.com/gajus/eslint-plugin-jsdoc/issues/1277 was resolved.

fix: unpin eslint-plugin-jsdoc
